language: python
python:
  - 3.6
script:
  - python setup.py build
deploy:
  provider: pypi
  user: $USERNAME
  password: $USERPASSWORD
  on:
    tags: true
    distributions: sdist
    repo: bashkirtsevich/py3bencode
